# Generated by Django 4.0.2 on 2022-09-08 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=180, verbose_name='Название продукта')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('file_attachment', models.FileField(upload_to='', verbose_name='Файл-аттачмент')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prosto_product_type', models.CharField(max_length=150, verbose_name='Тип продукта')),
            ],
        ),
        migrations.CreateModel(
            name='MoreAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адреса')),
                ('many_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.delivery', verbose_name='Множественные адреса')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='product_type',
            field=models.ManyToManyField(related_name='tags', to='polls.ProductType', verbose_name='Тип продукта'),
        ),
    ]
